//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralDasOngs.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesError() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentralDasOngs.Exceptions.ResourceMessagesError", typeof(ResourceMessagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP invalido..
        /// </summary>
        public static string CEP_INVALIDO {
            get {
                return ResourceManager.GetString("CEP_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade invalida..
        /// </summary>
        public static string CIDADE_INVALIDA {
            get {
                return ResourceManager.GetString("CIDADE_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ invalido..
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento invalido..
        /// </summary>
        public static string COMPLEMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("COMPLEMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF invalido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descricação invalida.
        /// </summary>
        public static string DESCRICAO_INVALIDA {
            get {
                return ResourceManager.GetString("DESCRICAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail é inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este e-mail já esta cadastrado..
        /// </summary>
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado invalido..
        /// </summary>
        public static string ESTADO_INVALIDO {
            get {
                return ResourceManager.GetString("ESTADO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome invalido..
        /// </summary>
        public static string NOME_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero invalido..
        /// </summary>
        public static string NUMERO_INVALIDO {
            get {
                return ResourceManager.GetString("NUMERO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do País é invalido.
        /// </summary>
        public static string PAIS_INVALIDO {
            get {
                return ResourceManager.GetString("PAIS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referencia invalida..
        /// </summary>
        public static string REFERENCIA_INVALIDA {
            get {
                return ResourceManager.GetString("REFERENCIA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua invalida..
        /// </summary>
        public static string RUA_INVALIDA {
            get {
                return ResourceManager.GetString("RUA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não é valida, deve possuir pelo menos 1 caractere especial, 1 numero, 1 letra maiúscula, 1 letra minúscula e entre 8 dígitos..
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas não são iguais..
        /// </summary>
        public static string SENHA_NAO_COINCIDE {
            get {
                return ResourceManager.GetString("SENHA_NAO_COINCIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha incorretos..
        /// </summary>
        public static string USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("USUARIO_INVALIDO", resourceCulture);
            }
        }
    }
}
